#!/bin/bash
# NOTE: This is an Information-modified version of the original tomesh script

set -e

# Set wireless regulatory domain
sudo iw reg set CA

# Select physical device that supports 802.11s Mesh Point
mesh_phy=phy0
mesh_dev=$(iw dev | grep phy#0 -A 1 | grep Interface | awk '{print $2}')

# Shut down the mesh_dev interface
sudo ifconfig $mesh_dev down

# Create a new mesh interface
iw dev $mesh_dev interface add MESH_NAME type mp

# Convert mesh_dev to 802.11s Mesh Point interface
sudo iw $mesh_dev set type mp

# Bring up the mesh_dev interface
sudo ifconfig $mesh_dev up

# Optionally assign IPv4 address to the mesh_dev interface
sudo ifconfig $mesh_dev 192.168.3.10

# Join the mesh network with radio in HT40+ htmode to enable 802.11n rates
sudo iw dev $mesh_dev mesh join MESH_NAME
#sudo iw dev $mesh_dev mesh join MESH_NAME freq 2412 HT40+

# Disable forwarding since we rely on cjdns to do routing and only uses Mesh Point as a point-to-point link
sudo iw dev $mesh_dev set mesh_param mesh_fwding=0

# Prevent trying to establish connections with nodes under -65 dBm
sudo iw dev $mesh_dev set mesh_param mesh_rssi_threshold -65

# Restart cjdns
sudo killall cjdroute
